CREATE TABLE IF NOT EXISTS public.config
(
    id                   bigint,
    bombardier           varchar(255),
    bombardier_points    integer,
    calendar             varchar(255),
    champion_points      integer,
    cup_eight_end        varchar(255),
    cup_eight_start      varchar(255),
    cup_end              varchar(255),
    cup_four_end         varchar(255),
    cup_four_start       varchar(255),
    cup_groups_end       varchar(255),
    cup_start            varchar(255),
    cup_time_preview     integer,
    difference           integer,
    difference_play_off  integer,
    host                 varchar(255),
    next_round_play_off  integer,
    place                integer,
    prognosis_quarter    integer,
    prognosis_semi       integer,
    score                integer,
    score_play_off       integer,
    src                  varchar(255),
    teams                varchar(255),
    testing              boolean,
    time_end_site_show   varchar(255),
    time_start_site_show varchar(255),
    time_test_now        varchar(255),
    time_test_start      varchar(255),
    title                varchar(255),
    url                  varchar(255),
    winner               integer,
    winner_play_off      integer,
    year_matches         integer
);

INSERT INTO public.config (id, bombardier, bombardier_points, calendar, champion_points, cup_eight_end, cup_eight_start, cup_end, cup_four_end, cup_four_start, cup_groups_end, cup_start, cup_time_preview, difference, difference_play_off, host, next_round_play_off, place, prognosis_quarter, prognosis_semi, score, score_play_off, src, teams, testing, time_end_site_show, time_start_site_show, time_test_now, time_test_start, title, url, winner, winner_play_off, year_matches) VALUES (1, 'bomb.htm', 6, 'calendar.htm', 8, '22:00 29.06', '19:00 26.06', '22:00 11.07', '22:00 03.07', '19:00 02.07', '22:00 23.06', '22:00 11.06', 1, 2, 3, 'https://football.kulichki.net', 1, 1, 2, 4, 4, 5, 'http://fnkimages.net/trans/flags', 'teams', false, '6:00', '18:00', '22:00 10.08.2021', '21:25 02.05.2021', 'Чемпионат Европы по футболу', 'euro/2016', 1, 1, 2021);